# pubspec.yaml (Updated Code)
name: jersey_premier_league_backend
description: A custom REST API for the JPL Flutter app using Dart and PostgreSQL.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.7.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^2.5.3 # <--- MUST BE PRESENT!
  bcrypt: ^1.1.3
  dotenv: ^4.0.0
  http: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1